//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickMe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDB
    {
        public int Emp_id { get; set; }
        public Nullable<int> Company_id { get; set; }
        public string Emp_fname { get; set; }
        public string Emp_lname { get; set; }
        public string Emp_contact { get; set; }
        public string Emp_email { get; set; }
        public string Emp_address { get; set; }
    }
}
