//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickMe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiclesDB
    {
        public int Vehicle_id { get; set; }
        public string Vehicle_regno { get; set; }
    }
}
